# Categories of applications
[categories]

[[categories]]
name = "Browsers" # Category name
  [[categories.options]]
  name = "Microsoft Edge" # Application name
  wingetId = "Microsoft.Edge"
  
  [[categories.options]]
  name = "Google Chrome"
  wingetId = "Google.Chrome"
  
  [[categories.options]]
  name = "Mozilla Firefox"
  wingetId = "Mozilla.Firefox"
  
  [[categories.options]]
  name = "Vivaldi"
  wingetId = "Vivaldi.Vivaldi"
  
  [[categories.options]]
  name = "Brave"
  wingetId = "Brave.Brave"
  
  [[categories.options]]
  name = "Opera"
  wingetId = "Opera.Opera"
  
  [[categories.options]]
  name = "OperaGX"
  wingetId = "Opera.OperaGX"

[[categories]]
name = "Development" # Category for development tools
  [[categories.options]]
  name = "Notepad++"
  wingetId = "Notepad++.Notepad++"
  
  [[categories.options]]
  name = "Visual Studio Code"
  wingetId = "Microsoft.VisualStudioCode"
  
  [[categories.options]]
  name = "Sublime Text 4"
  wingetId = "SublimeHQ.SublimeText.4"
  
  [[categories.options]]
  name = "Atom"
  wingetId = "GitHub.Atom"
  
  [[categories.options]]
  name = "Visual Studio Community 2022 Preview"
  wingetId = "Microsoft.VisualStudio.2022.Community.Preview"
  
  [[categories.options]]
  name = "Unity 2022"
  wingetId = "Unity.Unity.2022"
  
  [[categories.options]]
  name = "PyCharm Community Edition"
  wingetId = "JJetBrains.PyCharm.Community"
  
  [[categories.options]]
  name = "Visual Studio Code Insiders"
  wingetId = "Microsoft.VisualStudioCode.Insiders"

[[categories]]
name = "Utilities" # Category for utility tools
  [[categories.options]]
  name = "7-Zip"
  wingetId = "7zip.7zip"
  
  [[categories.options]]
  name = "WinRAR"
  wingetId = "Rarlab.WinRAR"
  
  [[categories.options]]
  name = "Corsair iCUE"
  wingetId = "Corsair.iCUE.5"
  
  [[categories.options]]
  name = "MSI Afterburner"
  wingetId = "Guru3D.Afterburner"
  
  [[categories.options]]
  name = "ShareX"
  wingetId = "ShareX.ShareX"
  
  [[categories.options]]
  name = "TeraCopy"
  wingetId = "CodeSector.TeraCopy"
  
  [[categories.options]]
  name = "OBS Studio"
  wingetId = "OBSProject.OBSStudio"
  
  [[categories.options]]
  name = "StreamLabs OBS"
  wingetId = "Streamlabs.StreamlabsOBS"
  
  [[categories.options]]
  name = "Chatterino"
  wingetId = "ChatterinoTeam.Chatterino"
  
  [[categories.options]]
  name = "SteelSeries GG"
  wingetId = "SteelSeries.GG"
  
  [[categories.options]]
  name = "Logitech G HUB"
  wingetId = "Logitech.GHUB"
  
  [[categories.options]]
  name = "Logitech Options"
  wingetId = "Logitech.Options"
  
  [[categories.options]]
  name = "HWINFO"
  wingetId = "REALiX.HWiNFO"
  
  [[categories.options]]
  name = "NZXT CAM"
  wingetId = "NZXT.CAM"
  
  [[categories.options]]
  name = "Microsoft PowerToys [Preview]"
  wingetId = "Microsoft.PowerToys"

[[categories]]
name = "Communication" # Category for communication tools
  [[categories.options]]
  name = "Discord"
  wingetId = "Discord.Discord"
  
  [[categories.options]]
  name = "Slack"
  wingetId = "SlackTechnologies.Slack"
  
  [[categories.options]]
  name = "Microsoft Teams"
  wingetId = "Microsoft.Teams"
  
  [[categories.options]]
  name = "Zoom"
  wingetId = "Zoom.Zoom"

[[categories]]
name = "Game Launchers" # Category for game launchers
  [[categories.options]]
  name = "Steam"
  wingetId = "Valve.Steam"
  
  [[categories.options]]
  name = "GOG Galaxy"
  wingetId = "GOG.Galaxy"
  
  [[categories.options]]
  name = "Epic Games Launcher"
  wingetId = "EpicGames.EpicGamesLauncher"
  
  [[categories.options]]
  name = "Ubisoft Connect"
  wingetId = "Ubisoft.Connect"
  
  [[categories.options]]
  name = "Bethesda.net Launcher"
  wingetId = "Bethesda.Launcher"
